FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io && \
    groupadd -f docker && \
    usermod -aG docker jenkins && \
    apt-get clean

ENV DOCKER_HOST=tcp://host.docker.internal:2375

USER jenkins
