FROM jenkins/jenkins:lts

USER root

# Instalar Docker CLI y configurar grupo
RUN apt-get update && \
    apt-get install -y docker.io && \
    groupadd -f docker && \
    usermod -aG docker jenkins && \
    apt-get clean

USER jenkins